### ISSUE TITLE
s3-to-streams

### ISSUE THREAD

**Issue by rohandora** [awslabs/amazon-kinesis-client#100]
Hi,I want to load data to kinesis analytics using schema free solution.This is possible if data is in delivery stream through  DiscoverInputSchema.

However , i have archival data in s3 bucket .We can use reference table,but the issue using reference table is that,schema needs to be specified explicitly.

So,is there a work around, i.e i load data from s3 into a delivery stream and configure firehose to deliver that data to kinesis analytics.

**Comment by rnienhuis** [comment]
Hello - My name is Ryan and I work for the Amazon Kinesis team. 

We need to structure your data in some way in order to expose it to your SQL code. Both reference and  streaming data sources require a schema to do this. The DiscoverInputSchema API samples data from your stream, and then recommends a schema to you for which you can update your application. 

We don't support an S3 bucket/object in the DiscoverInputSchema API. If we did, would this solve your issue?

Now, the workaround is a valid one albeit painful. You could also update the schema yourself with the new columns, but this likely has to be done manually.

**Comment by pfifer** [comment]
Thanks for your question I'm going to close this for now.

If you further questions please feel free to reopen this.
