### ISSUE TITLE
Configuring RetrievalConfig with InitialPosition

### ISSUE THREAD

**Issue by mrbalkan** [awslabs/amazon-kinesis-client#1100]
Hello,

I'm trying to set the initial position of a stream to TRIM_HORIZON with the below code:

InitialPositionInStreamExtended initialPositionInStreamExtended = InitialPositionInStreamExtended.newInitialPosition(InitialPositionInStream.TRIM_HORIZON);
   	    RetrievalConfig retrievalConfig = configsBuilder.retrievalConfig().retrievalSpecificConfig(new PollingConfig(STREAM_NAME, kinesisClient));
   	    retrievalConfig.initialPositionInStreamExtended(initialPositionInStreamExtended);

However, compiler complains "The method initialPositionInStreamExtended(InitialPositionInStreamExtended) from the type RetrievalConfig is deprecated"

How can I set it with the new way?

Thanks!

**Comment by stair-aws** [comment]
@mrbalkan Salut! From the Javadoc on `RetrievalConfig`: https://github.com/awslabs/amazon-kinesis-client/blob/e3d845a1f517fbe2c6760aa7740a103668075c0f/amazon-kinesis-client/src/main/java/software/amazon/kinesis/retrieval/RetrievalConfig.java#L144-L149

While the code you have works (for now), it may be removed in a future release. Instead, it would be forward-looking to subclass the `SingleStreamTracker` -- assuming, based on provided code snippet, you are processing a single stream, otherwise subclass `MultiStreamTracker` -- and override `orphanedStreamInitialPositionInStream()`: https://github.com/awslabs/amazon-kinesis-client/blob/e3d845a1f517fbe2c6760aa7740a103668075c0f/amazon-kinesis-client/src/main/java/software/amazon/kinesis/processor/StreamTracker.java#L62-L64

You then provide that instance to `ConfigsBuilder` via constructor or setter: https://github.com/awslabs/amazon-kinesis-client/blob/e3d845a1f517fbe2c6760aa7740a103668075c0f/amazon-kinesis-client/src/main/java/software/amazon/kinesis/common/ConfigsBuilder.java#L185-L189

After that, `configsBuilder.retrievalConfig().retrievalSpecificConfig(...)` -- and the rest of KCL -- should consistently yield the desired behavior.

**Comment by stair-aws** [comment]
With the PR, a subclass is no longer necessary to provide a consistent orphaned position. You can leverage the existing `InitialPositionInStreamExtended`-aware constructors: https://github.com/awslabs/amazon-kinesis-client/blob/e3d845a1f517fbe2c6760aa7740a103668075c0f/amazon-kinesis-client/src/main/java/software/amazon/kinesis/processor/SingleStreamTracker.java#L60-L70

**Comment by stair-aws** [comment]
Due to risk of impact, I closed the PR. If you need to maintain consistency between initial and orphaned positions, see the pseudo-code snippet in previous comment. If you don't require that consistency, creating the `StreamTracker` should be as simple as invoking a constructor: https://github.com/awslabs/amazon-kinesis-client/blob/e3d845a1f517fbe2c6760aa7740a103668075c0f/amazon-kinesis-client/src/main/java/software/amazon/kinesis/processor/SingleStreamTracker.java#L60-L70
