### ISSUE TITLE
Will KCL start new workers after resharding even if current shard is behind?

### ISSUE THREAD

**Issue by devshorts** [awslabs/amazon-kinesis-client#114]
I'm using KCL 1.6.2 and had 1 shard for a stream with 24 hour retention. I had a worker that fell behind in the stream and so I went to reshard to 4 shards. However, I didn't see new workers kick in until after the 24 hour period expired.

Reading http://docs.aws.amazon.com/streams/latest/dev/kinesis-using-sdk-java-after-resharding.html there is a quote that says

> If you are reading data using the Amazon Kinesis Client Library, the library ensures that you receive the data in order even if a reshard occurs.

Does this mean that the KCL won't spin up new workers unless the current shard is fully read and closed?  If thats the case what is the scaling strategy here?

**Comment by jqr** [comment]
Fellow user here. Yep, the child shards won't be processed until the parent shard is completed. The same thing happens on merging shards as well.

Since shards are cheap, my project tends to run an excess of shards (say 10 instead of 5) so that we can work around this and other operational issues. Of course this has the a negative side effect of sharding the data too much, but it means our margin of safety is much higher.

We also monitor latency on a per-shard basis and have alerts around it to scale, but once latency comes into play it may already be too late (especially if shard scaling is not automated). A better metric to monitor is "shard utilization" or the percentage of time your shard is processing the stream vs waiting. As this metric hits 100% you will see latency, but you can alert/scale on it hitting a lesser number like 50% which will side-step the latency.

**Comment by pfifer** [comment]
What @jqr said is correct the KCL will finish a parent shard before attempting to start any child shards.

As to handling events like this in the future the best approach is to have some additional capacity so that the KCL has extra capacity it can use.  This will ensure that if something causes your application to no longer make process, like a bug causing a crash, you have enough capacity to catch up.  There are two common scenarios for falling behind and catch up:

1. Your application has slowed down, but is making some forward progress
   1. You can [increase the retention period for the stream](http://docs.aws.amazon.com/streams/latest/dev/kinesis-extended-retention.html), this will allow your application to continue to process data after the normal 24 hour window.  This means you eventually catch up, but data will still be delayed.  If you want to begin processing new data, while still processing old data there are some other options.
      1. You can start your application up, with a new application name which will create a new lease table, and checkpoint status.  If you use a time based iterator this will allow the application to start at a later point in the underlying shard.
      2. Create a new stream, and update your producers to send to that stream.  At the same time launch your application, with a new application name, for that stream.
2. If you application isn't catching up at all your sort of stuck with a few bad options
   1. Figure out if it's possible to have your application skip some processing, either by just storing data for later processing or just dropping it.  You would want to modify your application logic to detect when it's caught up, and begin normal processing then.
   2. You might try slowing down your producers if that is possible.  Your application may be able to make more forward progress then.
   3. If you're comfortable dropping the older data your can use [time-based iterators](https://aws.amazon.com/about-aws/whats-new/2016/04/amazon-kinesis-streams-introduces-time-based-shard-iterators-and-shard-level-metrics/) to select an approximate point in time that you want your application to start from.  If you do this you will need to remove the checkpoint data from the application's DynamoDB table. After removing the checkpoint information the KCL will start from the selected time, instead of starting from the last checkpoint value.

**Comment by devshorts** [comment]
@jqr @pfifer thanks for the response, this was very helpful. I appreciate it.

@pfifer can you expand on time based iterators? How is that configured?

**Comment by pfifer** [comment]
The initial coverage from the release notes give a good idea about the time-based iterators:
* Add support for time based iterators ([See GetShardIterator Documentation](http://docs.aws.amazon.com/kinesis/latest/APIReference/API_GetShardIterator.html))
  * [PR #94](https://github.com/awslabs/amazon-kinesis-client/pull/94)
  The `KinesisClientLibConfiguration` now supports providing an initial time stamp position.
  * This position is only used if there is no current checkpoint for the shard.
  * This setting cannot be used with DynamoDB Streams
  Resolves [Issue #88](https://github.com/awslabs/amazon-kinesis-client/issues/88)

The big caveat with this is it only takes affect if there is no existing checkpoint for the shard.  In your case you would need to make the configuration change, deploy, and then remove the lease information from the DynamoDB table.
