### ISSUE TITLE
It should be possible for IRecordProcessors to mark themselves for shutdown.

### ISSUE THREAD

**Issue by llamahunter** [awslabs/amazon-kinesis-client#12]
For various reasons, an IRecordProcessor should be able to decide it should be shut down.  This could be due to an unrecoverable error, or it could be part of coordinated load balancing.

 It should either a) be able to return a code from processRecords() to indicate it should be marked for shutdown, or b) have an object on which it can request a shutdown. Currently, the only object it has a pointer to is the IRecordProcessorCheckpointer.  It seems a little strange to put a shutdown() method on that interface.

**Comment by coldear** [comment]
This is exactly what I am looking for. 
Ideally, when user request to destroy current processor, KCL should be able to create a new one for the same shards and start to process from the last checkpoint.

**Comment by ridha** [comment]
+1

**Comment by rhodey** [comment]
you can accomplish this pretty easily with Guava's ListenableFuture or Java8's CompletableFuture & the factory pattern & I'm happier with this being app-specific logic instead of something forced by the library-- amz has a history of doing threading & executors weird :/

you already have to implement `IRecordProcessorFactory` but give yourself a base abstract pattern to start, like my [KinesisRecordConsumerFactory](https://github.com/rhodey/kinesis-common/blob/85f2f76b9e825fa398ca32d65706ff840b5d138c/src/main/java/org/anhonesteffort/kinesis/consumer/KinesisRecordConsumerFactory.java)

my [KinesisRecordConsumer](https://github.com/rhodey/kinesis-common/blob/af2f8e68fa506c036075b5d15c3ee6eb063737a9/src/main/java/org/anhonesteffort/kinesis/consumer/KinesisRecordConsumer.java) has some application specific stuff in there but you should be able to get the idea.

then in your main class add a callback to `KinesisRecordConsumerFactory.getErrorFuture()` & kill your app or shutdown your worker or whatever you want.

**Comment by jqr** [comment]
It would be great for the MLD to have this as well. We're currently calling `exit(1)` which works, but also causes the whole MLD to die, taking all owned shards with it. Restarting with `workerId` means these come back up quickly, but it's overkill.

**Comment by pfifer** [comment]
Thanks for reporting this.  We're investigating this feature, and will prioritize with other feature requests.

Others - Please comment or add your reaction to this post so our team is aware of how to prioritize this change.

**Comment by BobbyJohansen** [comment]
I would agree with this seems like an important piece of functionality to provide to the implementer

**Comment by zeynepsu** [comment]
We're tracking this internally. Closing this issue.
