### ISSUE TITLE
KCL2 -Multi stream consumer - Configured streams can be in same account and cross account

### ISSUE THREAD

**Issue by Chaitanyasharma1989** [awslabs/amazon-kinesis-client#1250]
In my project there is a requirement of a KCL2 multi stream consumer which is consuming from streams which are both in same AWS account and cross account.
Is there any way to achieve this configuration using java as I can see that we cannot have multiple config builder for kinesis client with different credential provider as for cross account we need to have
StsAssumeRoleCredentialsProvider and for same account we can have default credential provider?
Please suggest

**Comment by brendan-p-lynch** [comment]
In order to use a multi-stream consumer with two different streams you will need to set up an IAM role in the account that has access to the stream in that account and in the second account (let's call it account B). 

You will then have to configure the stream to be accessed by the role that was created in the original account. 

This should satisfy the requirements laid out above.

**Comment by Chaitanyasharma1989** [comment]
I am not sure if this will work as for any stream which is cross account i will be having kinesis async client with sts credential provider and for stream which is in se account it will be default credential provider.

Are you saying that we need to have multiple scheduler depending on the type of stream or there is any configuration which we are missing?

Thanking in anticipation

**Comment by Chaitanyasharma1989** [comment]
For cross account we need to have sts credential provider and to access same account stream we need default credential provider.

As per my understanding we have to use sts credential provider for cross account stream access. If there is any understanding gap please let us know.
