### ISSUE TITLE
Docs for MultiLang don’t describe error handling

### ISSUE THREAD

**Issue by aviflax** [awslabs/amazon-kinesis-client#21]
It’s not clear to me how my child process should handle errors. If an error is encountered while processing a batch of records, what should the child process do? Exit with an error exit code? Or… what? And how will the MultiLangDaemon (MLD) handle such a case?

I’m hoping that there’s some way to gracefully handle errors and prompt the MLD to retry a batch, but it’s not clear. I’ve been reading the source but my Java is rusty and I’d appreciate some help.

Thanks!

**Comment by jqr** [comment]
Kinesis user here, and I've done some extensive testing of this particular problem and talked to the AWS Kinesis subject matter experts about our use-case.

Currently we're using `exit(1)` when an unrecoverable error is encountered. This has the effect of causing the `MultiLangDaemon` to exit, along with any other record processors it was executing.

We have another process monitoring the `MultiLangDaemon` so it restarts immediately and because we set `workerId`, it retains it's leases and starts new record processors for the leases it still has very quickly.

This is a great approach if you have idempotent writes because it is a 10 second latency bump for us.

If you're using > 1 record processor per `MultiLangDaemon` and you cannot handle receiving the same record twice, you are going to have a hard time :)

**Comment by aviflax** [comment]
@jqr thanks so much for sharing! I really appreciate it! I’ve taken a temporary break from experimenting with the MLD to spend some time experimenting with Lambda, but if/when I switch back to MLD your experience will be hugely helpful. Thank you!

**Comment by aviflax** [comment]
Whelp, looks like I’m back to the KCL-MLD because Lambda doesn’t support VPC. So, thanks again!

**Comment by aviflax** [comment]
(I’d still love to see the docs updated.)

**Comment by aviflax** [comment]
Just to close this out, I spoke with Adi Krishnan and Rahul Patil of the Kinesis team last week, and they confirmed that the child process should just exit when it encounters an error, and that setting `workerId` is optional but a good idea. Thanks!
