### ISSUE TITLE
KCL not processing records from one out of two shards of AWS kinesis stream

### ISSUE THREAD

**Issue by awadeshmmm** [awslabs/amazon-kinesis-client#290]
I have a kinesis stream with two shards and i am running it in Eclipse on my machine.I am able to see that records are published to all two shards but our kinesis consumer application is able to process records from only one shard. Workers listening to other  shard is constantly going to sleep.

**Comment by sahilpalvia** [comment]
@awadeshmmm can you provide more information about your issue.
1. How many KCL instances are you running?
1. How long did you conduct your test for?
1. Were you reading from LATEST or TRIM_HORIZON?

According to your description you have a stream with 2 shards, but you are trying to read from 3. Can you clarify that?

**Comment by awadeshmmm** [comment]
@sahilpalvia I am running only one instance of KCL. Stream is with 2 shards. Actually i have figured it out there was **bufferMillisecondsLimit** which was set to 60 minutes. And i was doing testing with 10 records. so none of the criteria was going to satisfy to emit the records. 

If i am not wrong this was the reason it was going to sleep for long time and records were not emitted to S3. Kindly correct me if i am wrong.
 Thanks

**Comment by sahilpalvia** [comment]
Is this an issue with the KCL or the connectors [amazon-kinesis-connectors](https://github.com/awslabs/amazon-kinesis-connectors)? If the issue is with the connectors, could you open an issue in that repository so that it can be tracked and resolved. On scanning the connector library, it seems like `bufferMillisecondsLimit` value is used in the [shouldFlush](https://github.com/awslabs/amazon-kinesis-connectors/blob/master/src/main/java/com/amazonaws/services/kinesis/connectors/impl/BasicMemoryBuffer.java#L108-L112) method. Feel free to reopen the issue if the issue persists with the KCL.
