### ISSUE TITLE
Detected spurious renewal failure for lease with key shardId-000000000000, but recovered

### ISSUE THREAD

**Issue by cwei-bgl** [awslabs/amazon-kinesis-client#325]
Hi,

I saw many in my logs - "Detected spurious renewal failure for lease with key shardId-000000000000, but recovered". What does this mean? Thanks.

Cheng

**Comment by sahilpalvia** [comment]
@cwei-bgl This just means that the last update to DynamoDB returned a 500 from the service, but the update was successful in making the changes to the table. Before this fix, such issues would cause the Worker to lose the lease and wait for it to be picked up by any Worker and start processing the records again. This fix avoids lease losses and lease shuffling due to 500s from DynamoDB service when the update was successful.

This happens only if the last update to DynamoDB returned a 500, if there are DynamoDB consistently returns 500s the worker will lose the lease.

Closing the issue, feel free to reopen the issue if you have more questions.

**Comment by adrian-baker** [comment]
Internal stuff like this doesn't seem like it belongs at INFO log level.
