### ISSUE TITLE
TRIM_HORIZON vs LATEST

### ISSUE THREAD

**Issue by idaamit** [awslabs/amazon-kinesis-client#327]
I can't find in the documentation any reference between `TRIM_HORIZON`  and the checkpoint, and also any reference between `LATEST` and the checkpoint.

Can you confirm my theory:

* `TRIM_HORIZON` - In case the application-name is new, then I will read all the records available in the stream. Else, application-name was already used, then I will read from ***my*** last checkpoint.

* `LATEST` - In case the application-name is new, then I will read all the records in the stream which added ***after*** I subscribed to the stream. Else, application-name was already used, I will read messages from ***my*** last checkpoint. 

* **The difference between `TRIM_HORIZON` and `LATEST` is only in case the application-name is new.**

**Comment by pfifer** [comment]
The KCL will always use the value in the lease table if it's present.  It's important to remember that Kinesis itself doesn't track the position of consumers.  Tracking is provided by the lease table.  Leases in the KCL server double duty.  They provide both mutual exclusion, and position tracking.    So for mutual exclusion a lease needs to be created, and to satisfy the position tracking an initial value must be selected.

From your last point:
> * The difference between `TRIM_HORIZON` and `LATEST` is only in case the application-name is new.

This can be formalized to:
* When the KCL needs to create a new lease:
  * If the shard that the lease is being created for has a parent, and that parent has a lease in the lease table it will create the lease at `TRIM_HORIZON`
  * Otherwise it will create the lease at the value configured in `initialPositionInStream`

If you ever want to restart your processing you have some options.  In all of these cases it's best to shutdown the application before doing them.  
* Delete the leases from the lease table.
  * As long as `skipShardSyncAtWorkerInitializationIfLeasesExist` is false the KCL will recreate the leases.
* Delete all the leases from the lease table, they should be recreated at application startup.
* Delete the lease table.  The table, and leases should be recreated at startup.
* Use a different application table.  This effectively acts like deleting the lease table as the KCL will create a new lease table, and leases, for the application name.

Feel free to reopen this if you have anymore questions.


* Delete the lease table

**Comment by stavalfi** [comment]
@pfifer nice answer! Can you also explicitly indicate if OP's assumptions are right?

**Comment by markthegrea** [comment]
> I can't find in the documentation any reference between `TRIM_HORIZON` and the checkpoint, and also any reference between `LATEST` and the checkpoint.
> 
> Can you confirm my theory:
> 
> * `TRIM_HORIZON` - In case the application-name is new, then I will read all the records available in the stream. Else, application-name was already used, then I will read from _**my**_ last checkpoint.
> * `LATEST` - In case the application-name is new, then I will read all the records in the stream which added _**after**_ I subscribed to the stream. Else, application-name was already used, I will read messages from _**my**_ last checkpoint.
> * **The difference between `TRIM_HORIZON` and `LATEST` is only in case the application-name is new.**

This documentation belongs here:https://docs.aws.amazon.com/kinesis/latest/APIReference/API_StartingPosition.html
