### ISSUE TITLE
Worker::shutdown should notify when it finished

### ISSUE THREAD

**Issue by idaamit** [awslabs/amazon-kinesis-client#330]
If an error on has occurred during `Worker::shutdown` or it finished successfully, I would like to know what was the status.

**Comment by pfifer** [comment]
Instead of using shutdown I would recommend using [`Worker#startGracefulShutdown()`](https://github.com/awslabs/amazon-kinesis-client/blob/master/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/Worker.java#L794).   `Worker#startGracefulShutdown()` returns a future that can be used to detect the completion of the shutdown, and the outcome.

**Comment by lc-nyovchev** [comment]
@idaamit there is recently introduced a WorkerStateChangeListener which gives you a callback you can listen for a successful SHUT_DOWN state (see WorkerState.SHUT_DOWN)
