### ISSUE TITLE
Application consumers lagging behind (high MaxIteratorAgeMillis) when adding/killing consuming instances

### ISSUE THREAD

**Issue by Towerthousand** [awslabs/amazon-kinesis-client#332]
**# of streams**: 1
**# of workers**: 4-24 (autoscaled)
**KCL Version**: 1.8.10
**Event throughput**: 9k+/min

I have a bunch of java instances consuming from one stream. When I change the number of workers, even if it's only adding new workers, they steal leases from each other (which is understandable as a rebalance) causing spikes of up to 100k milliseconds on max iterator age, meaning some events take up to 100 seconds to be processed.

This used to be worse: Workers used to not renew leases in time which would mean constant stealing of leases and constant lag spikes. I solved that by increasing `failoverTimeMillis` to 20 seconds.

I can understand spikes of up to 20 seconds when adding/removing workers, since that's what `failoverTimeMillis` is set to, but what might be causing 100+ seconds of lag? And what might cause workers to take so long to renew their leases?

Is there a way to actively evict owned leases on shutdown? Is there a plan to allow such a feature?

I'm attaching some stats to illustrate the lag problem. I've searched the old issues but can't find the same problem, it seems.

Thank you!

<img width="461" alt="screen shot 2018-04-18 at 17 54 35" src="https://user-images.githubusercontent.com/3587309/38943424-b17e7d9e-4331-11e8-8074-85b13a396e0d.png">

**Comment by Towerthousand** [comment]
@pfifer hey man, sorry for the direct tag. Is this not the right place to ask for these issues? I tried AWS Support and they couldn't help me.

**Comment by pfifer** [comment]
The scale up issue is due to lease stealing, and could also just be to how leases end up shaking out in the process.  

During the scaling down process it's timing based.  Lease expiration is checked every time the lease taker runs, and the lease taker runs every `(failoverTimeMillis + epsilonMillis) * 2`, in your cases this is every 40 seconds.  If you unlucky enough that all your workers become synchronized, and a lease is lost just after the expiration check it can take up to 80 seconds before a lease is detected as lost.  

The second part is dependent on how you checkpoint.  When a lease is lost the new worker will start from the last checkpoint.  If you're checkpoints are far enough apart this can increase the delay. 

Lowering the lease failoverTimeMillis would help in this case.  The issues you had before might have been related to IOPs on the DynamoDB table.  If you want to lower the failover time I would check both the read, and write IOPs to ensure you have the capacity needed.

Lastly there is a possible issue with the lease taker code, in that it doesn't jitter.  If all of you're workers start up at the same time, it's likely that they will operate their lease takers in lock step.  Adding jitter to the lease taker is something we can take a look at, but I don't have a timeline of when that might occur.

**Comment by Towerthousand** [comment]
Thank you for the thorough answer.

I'll try bringing the `failoverTimeMillis` down again and measure again, checking the DynamoDB IOPs.

I take it from your answer that seeing a high Iterator age for new record processors is affected by my checkpointing in that if I checkpoint every 1 minute (which I do) and the lease gets stolen due to load balancing 1 second before the checkpoint, the new worker will reprocess that full minute again, so it doesn't necessarily mean it's taking 1 minute for an event to be processed for the first time, just that there are 1 minute old events being processed.

This, coupled with the up to 80 seconds before detecting a lease as lost, explains my graphs. As for the jitter, I'll add some manual random jittering to the worker startup code on my side.

Thank you again for the tips!
