### ISSUE TITLE
always start from LATEST

### ISSUE THREAD

**Issue by knap1930** [awslabs/amazon-kinesis-client#449]
Is there a way to configure KCL to always start from the LATEST instead of what is in the dynamodb table? 

My use case is I have one application that is consuming a stream and performing analytics / logging.. this one I want to process every record in the stream. I have this working well.

I have another application consuming the same stream, but it is just maintaining a redis cache. Unfortunately if a worker dies, it starts where it left off, and performs many unnecessary updates to the cache, causing it to take a while to catch up.

I know I could just delete the dynamodb table, but once I get to a point where I have multiple shards, with multiple workers.. and a single worker dies, I assume the running worker wouldn't appreciate having its table deleted. I just want to have the worker that dies start from LATEST when restarted.

**Comment by pfifer** [comment]
Thanks for the suggestion.  The KCL doesn't support this today, but supporting this is something we may consider adding in the future.  

For other please add a comment, or a reaction to the parent post to assist us in prioritizing this feature request.

**Comment by sahilpalvia** [comment]
@knap1930 What behavior do you expect when leases are being stolen due to load balancing? Are they expected to start from `LATEST` too? If that is the case, the one thing that you could try is not checkpointing ever and setting the initalposition to `LATEST`. Drop your lease table and let it be recreated. This way all leases would always be at `LATEST`. The checkpointed values from the lease table are use at start up and when leases are stolen.

**Comment by knap1930** [comment]
yes, that is ok with me, and is actually what I ended up doing to solve the issue.

the only issue I did notice was when scaling up the number of shards, it got stuck at the end of the closed shards, and never started processing the new ones. deleting the rows from the dynamodb table, and restarting the consumer solves the issue. haven't had time to dig in to why this happens. I assume its related to the checkpoint never switching over to SHARE_END.

**Comment by sahilpalvia** [comment]
Child shards are picked up for processing once the parent shard has finished. You will need to checkpoint in the shutdown method if the reason is `SHARD_END`. 

Child shard leases are created with `TRIM_HORIZON` as the checkpoint value. You may need a job that updates the lease checkpoint value to `LATEST` and force the worker to lose the lease by updating the `leaseOwner`.
