### ISSUE TITLE
[question] Process multiple Kinesis streams within single Java process

### ISSUE THREAD

**Issue by pr3mar** [awslabs/amazon-kinesis-client#491]
Hi,

I would like to process multiple Kinesis streams using KCL within the same Java process.

The idea is simple: make a new KCL instance for each stream and then run the workers concurrently.

My question is whether in this case all KCL instances are using the same thread pool, and whether this idea is a good/common practice when dealing with stream processing.

Thank you

**Comment by pr3mar** [comment]
ping @sahilpalvia, @pfifer

**Comment by pr3mar** [comment]
ping @sahilpalvia, @pfifer

**Comment by sahilpalvia** [comment]
There is no best practice for such a scenario. The requirement would be to have a threadpool large enough to be able to handle scheduling all threads. The only recommendation would be provide individual threadpools to each Worker/Scheduler so that any issues with the threadpool and scheduling is limited to a single application.

Closing the issue out. Please feel free to reopen if problem persists.
