### ISSUE TITLE
Failed to checkpoint record 

### ISSUE THREAD

**Issue by ASharma0502** [awslabs/amazon-kinesis-client#563]
Hi all,

We sometimes get Failed to checkpoint record exceptions while checkpointing to dynamodb. Does this cause loss of records or is it intermittent and the kcl library retries?

![image](https://user-images.githubusercontent.com/41919661/60362449-e7926100-99ae-11e9-9711-08f7231f4827.png)

**Comment by ashwing** [comment]
This generally happens when leases are picked up by another worker either due to rebalancing or the current worker unable to renew the lease. In both the cases the previous worker will unable to checkpoint when new worker has acquired the lease. Some records might be reprocessed based on your checkpointing interval, but no data loss will happen.
