### ISSUE TITLE
Kinesis Checkpoint Reverts on Reshard / Lease Creation

### ISSUE THREAD

**Issue by chrismagnacca** [awslabs/amazon-kinesis-client#580]
**Kinesis Client Version**: software.amazon.kinesis:amazon-kinesis-client:2.2.0

**Issue**

Upon resharding, Kinesis Consumers will begin to create leases at TRIM_HORIZON and not at the preset InitialPositionInStreamExtended, despite the ConfigsBuilder's leaseManagementConfig and retrievalConfig both specifying alternative checkpoint strategies. 

** Reproduction Steps

* prerequisite setup : Assuming a basic KCL 2.X setup consuming off a Kinesis Stream with a retrievalConfig and (optional) leaseManagementConfig set to LATEST InitialPositionInStreamExtended (whether or not the leaseManagement is set is irrelevant as it happens whether or not it's set)

* notice that leases will be initialized with LATEST when an application spins up

* kick off a reshard by adding or removing shards from the stream. This event will create SHARD_END on the closed shards and TRIM_HORIZON checkpoints on the new shards despite configs settings set for retrieval or lease config on the configsBuilder.

* result : leases repopulate in the table as TRIM_HORIZON and slowly revert LATEST checkpoints on old leases into TRIM_HORIZON

The expected behavior (imo) would be for resharding to respect the leaseManagementConfiguration setting for InitialPositionInStream, rather than default to TRIM_HORIZON as I could not find if this was documented in the Kinesis Documentation or KCL documentation.

**Comment by sahilpalvia** [comment]
This is an expected behavior. The KCL will finish processing records from the parents and then will start processing the records from the children. If the application is not at `LATEST` all the time, at `SHARD_END` if the child is initialized with `LATEST` it will cause data loss. `TRIM_HORIZON` for child shards at resharding ensures that all the records from the shard are read.

Closing the issue out, feel free to reopen if problem persists.

**Comment by chrismagnacca** [comment]
@sahilpalvia thank you for the clarity, however this will eventually pollute the DynamoDB lease table and will (over time) result in the entirety of the table being back at TRIM_HORIZON as a result of the reshard and leases shuffled over time. Combined with the fact that the KCL prioritizes the lease table over its own configsBuilder, this would result in replays in almost every situation following a reshard. 

I believe this behavior makes sense if the specified position in stream can actually effect existing leases, which it cannot. Thus if you do not want replayed data, you must manage this outside the Kinesis ecosystem by modifying the Dynamo table. It seems like a bit of an issue with the design of the Consumer library and/or the precedence in which is honors leases. I understand this is how it functions now though. Are there any suggestions when you would not want replays of processed records? As it stands, if I reshard and release the application again, consumers will inevitably replay data on the leases with TRIM_HORIZON.

**Comment by sahilpalvia** [comment]
I think your application is missing the checkpointing feature. If you checkpoint after processing the records the `checkpoint` value in the dynamodb table gets updated to the last sequence number of the record that the application have processed. This is how a KCL application stores its state so that when a lease gets stolen or the application is restarted the lease isn't replaying the records that have already been processed.

The application can access the [ProcessRecordsInput.checkpointer()](https://github.com/awslabs/amazon-kinesis-client/blob/master/amazon-kinesis-client/src/main/java/software/amazon/kinesis/lifecycle/events/ProcessRecordsInput.java#L62) to get the checkpointer object and checkpoint with a value. The [RecordProcessorCheckpointer](https://github.com/awslabs/amazon-kinesis-client/blob/master/amazon-kinesis-client/src/main/java/software/amazon/kinesis/processor/RecordProcessorCheckpointer.java) supports various ways of checkpointing. The [ShardRecordProcessorCheckpointer](https://github.com/awslabs/amazon-kinesis-client/blob/master/amazon-kinesis-client/src/main/java/software/amazon/kinesis/checkpoint/ShardRecordProcessorCheckpointer.java) is the implementation provided by the KCL.
