### ISSUE TITLE
v1.9.0 zombie shutdown when rebalancing shards across mld's

### ISSUE THREAD

**Issue by tameemanwar** [awslabs/amazon-kinesis-client#639]
Versions - 1.9.0
Setup = 40 shards split across 2 MLD's instances

Scenario - When adding 2 new MLD instances, the 40 shards get distributed across all the MLD instances and this causes new MLD instances to steal shards from existing one's. This results in zombie shutdown on the existing KCL processes that owned the shards. The problem with a zombie shutdown is that we cannot checkpoint. What is the recommended approach here ? Anyway we can get a graceful shutdown here ?

**Comment by MihirLimbachia** [comment]
KCL is designed such that if there 2 KCL workers, eventually there will be stability in terms of number of shards each KCL worker processes.

If the KCL worker is not able to refresh lease (ownership of shard), than and than only the lease should be lost for that worker.

When the lease is lost, the record processor is terminated with ZOMBIE reason, indicating that the worker's record processor was acting like a ZOMBIE and did not refresh the lease for the shard it was processing.

So in case of your architecture, the two KCL workers, if they are healthy, should be processing 20 shards each and it should be quite stable without lease loss..

What I suspect is you might have the DDB write throughput set as quite low.. which is by default 10/s.

So worker might be getting throttled on updating the lease in the DDB table. and hence it might be losing leases.

https://github.com/awslabs/amazon-kinesis-client/blob/c696bc1862718f556b59ccbbef4592323543192a/amazon-kinesis-client-multilang/src/main/java/software/amazon/kinesis/coordinator/KinesisClientLibConfiguration.java#L17

Check the ExpiredLeases metric for KCL.. It should be high..

https://docs.aws.amazon.com/streams/latest/dev/monitoring-with-kcl.html

You may set the the write and read capacity to 20 using the provided functions in the KCL conifg class.

https://github.com/awslabs/amazon-kinesis-client/blob/c696bc1862718f556b59ccbbef4592323543192a/amazon-kinesis-client-multilang/src/main/java/software/amazon/kinesis/coordinator/KinesisClientLibConfiguration.java#L1213

https://github.com/awslabs/amazon-kinesis-client/blob/c696bc1862718f556b59ccbbef4592323543192a/amazon-kinesis-client-multilang/src/main/java/software/amazon/kinesis/coordinator/KinesisClientLibConfiguration.java#L1202

**Comment by tameemanwar** [comment]
thanks for getting back @MihirLimbachia ! I have two follow up questions

1) > KCL is designed such that if there 2 KCL workers, eventually there will be stability in terms of number of shards each KCL worker processes.
I agree. Let's say there are 2 workers `worker1` and `worker2` and 40 shards . I can see 20 shards per worker. Now let's say I decide to add 2 more workers `worker3` and `worker4`. What happens is all workers will eventually get 10 workers each, all makes sense. My question is when `worker1` goes from 20 shards to 10 shards, why does `10` of the child processes on `worker1` get zombie shutdown and not a normal shutdown. I am not changing the number of workers constantly on purpose but it can happen when we are doing a rolling upgrade or when we get new nodes (instances) and containers move around. Basically containers will come and go and each time this happens if we are going to get zombie shutdown in order to balance shards, it seems odd. 

2) > Check the ExpiredLeases metric for KCL.. It should be high..
Yes, I do observe this happens once or twice a day. Note this scenario is different from the above point. In this case all the workers are stable but still leases expire.  We actually use `On-Demand` read/write capacity mode. Do you think moving to `Provisioned mode` and that too with a higher capacity will help to avoid this ?

**Comment by MihirLimbachia** [comment]
KCL has been designed to re-distribute shards whenever new workers join the application.

Each worker processes certain shards and the ownership and processing information of that shard is maintained by a lease entry in a DDB checkpoint table.

So, whenever a new worker joins, it will try to steal the lease from the worker that has the most leases. Whenever a leases is stolen, KCL is designed to do a ZOMBIE shut down for the record processor that was processing the shard that was processing that lease.

KCL is designed to expect stable workers and if a new worker joins, by design  it restributes the load. 

If you would like each worker to get some specific number of leases, you may use withMaxLeasesForWorker method.

https://github.com/awslabs/amazon-kinesis-client/blob/c696bc1862718f556b59ccbbef4592323543192a/amazon-kinesis-client-multilang/src/main/java/software/amazon/kinesis/coordinator/KinesisClientLibConfiguration.java#L1176

You can also shutdown the old workers gracefully using the graceful shutdown method and than start off the new workers once the old workers are down properly..

 https://github.com/awslabs/amazon-kinesis-client/blob/3947b55853636703afc36f83f36f8d54adf199ec/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/Worker.java#L845

Moreover, it is recommended to checkpoint in the processRecords method at least once after the batch is processed.

https://docs.aws.amazon.com/streams/latest/dev/kinesis-record-processor-implementation-app-java.html#kcl-java-interface-original

This way, when a scaling event occurs, and there is zombie shutdown due to lease loss, the new worker can start off processing with the batch that the old worker's record processor failed to checkpoint due to ZOMBIE shutdown.

The On-Demand read/write capacity mode should be fine.

**Comment by tameemanwar** [comment]
thanks @MihirLimbachia !

> So, whenever a new worker joins, it will try to steal the lease from the worker that has the most leases. Whenever a leases is stolen, KCL is designed to do a ZOMBIE shut down for the record processor that was processing the shard that was processing that lease.

This is was my question, thanks for clarifying. 

> Moreover, it is recommended to checkpoint in the processRecords method at least once after the batch is processed.

We do this. 

> The On-Demand read/write capacity mode should be fine.

Thanks!
