### ISSUE TITLE
How to stop KCL when the credentials are expired?

### ISSUE THREAD

**Issue by xiaoshao** [awslabs/amazon-kinesis-client#71]
I get the record from kinesis in another account with the temp credentials. How to stop the KCL app when the credentials are expired?

**Comment by pfifer** [comment]
The KCL uses the AWS Java SDK which supports using [Credential Providers](http://docs.aws.amazon.com/java-sdk/latest/developer-guide/credentials.html).  The easiest of the credential providers to use is the [InstanceProfileCredentailsProviders](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html?com/amazonaws/auth/InstanceProfileCredentialsProvider.html) which will automatically rotate the credentials before they expire.  If you're using one of the other credential providers you would need to handle rotation yourself.  

The problem with stopping the KCL once credentials have expired is there is no way for the KCL to checkpoint its state, since it can no longer use the credentials to write to DynamoDB.  If you really want to implement stopping the KCL on the credentials expiration you could implement [AWSCredentialsProvider](http://docs.aws.amazon.com/AWSJavaSDK/latest/javadoc/index.html?com/amazonaws/auth/AWSCredentialsProvider.html), and have it notify the main thread to call [Worker#shutdown](https://github.com/awslabs/amazon-kinesis-client/blob/master/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/Worker.java#L478).  This would cause the record processors to be shutdown, but you would need to be careful calling the checkpointer methods due to expired credentials.
