### ISSUE TITLE
deletionThreadPool not closed in LeaseCleanupManager

### ISSUE THREAD

**Issue by yutian-wu** [awslabs/amazon-kinesis-client#796]
Greetings,

As we were using the KCL 2.3 recently, we noticed that even after the scheduler has been shut down, part of the ``LeaseCleanupManager`` is still running, continuously logging this message:

```
Number of pending leases to clean before the scan : 0
```

After looking into the source code along with thread dump, I found that ``deletionThreadPool`` in ``LeaseCleanupManager `` is never closed.

```java
deletionThreadPool.scheduleAtFixedRate(
  new LeaseCleanupThread(), INITIAL_DELAY, leaseCleanupIntervalMillis, TimeUnit.MILLISECONDS
);
```

More context at:

 https://github.com/awslabs/amazon-kinesis-client/blob/master/amazon-kinesis-client/src/main/java/software/amazon/kinesis/leases/LeaseCleanupManager.java#L88

So I am creating this issue to have the problem tracked.

Thanks,

**Comment by turcsanyip** [comment]
I ran into the same issue with KCL 1.
1.14.x cannot stop cleanly but `LeaseCleanupManager` keeps running forever.
Versions up to 1.13.3 can stop properly.

As far as I can see, the root cause is this:
https://github.com/awslabs/amazon-kinesis-client/blob/f38dd18ed1d41b9dd3839366d16a58b832292a0b/src/main/java/com/amazonaws/services/kinesis/clientlibrary/lib/worker/Worker.java#L579-L580

The `Worker` creates an `ScheduledExecutorService` for `LeaseCleanupManager` on the fly. As there is not reference to the executor, it cannot be stopped later.
